name: SMPnir
version: 0.1.4
main: com.nickrodi.nir.NirPlugin
api-version: "1.21.11"

commands:
  nir:
    description: SMPnir admin command.
    usage: /nir <debug|user> ...
    permission: smpnir.admin

  coords:
    description: Show your coordinates.
    usage: /coords
    aliases: [coordinates]
    permission: smpnir.use

  build:
    description: Submit builds for manual review.
    usage: /build <submit|groupsubmit|list|claim|submissions|history|grade>
    permission: smpnir.use

  questbook:
    description: Open your questbook.
    usage: /questbook
    aliases: [level, quests, book, progress, stats, statistics, b]
    permission: smpnir.use

  leaderboard:
    description: Show the top players.
    usage: /leaderboard
    permission: smpnir.use

  sleepvote:
    description: Vote to skip to day.
    usage: /sleepvote yes
    permission: smpnir.use

  smphelp:
    description: Show the welcome message.
    usage: /smphelp
    permission: smpnir.use

  xplist:
    description: Show all XP sources in the book.
    usage: /xplist
    permission: smpnir.use

permissions:
  smpnir.admin:
    description: Allows use of admin commands.
    default: op

  smpnir.use:
    description: Allows use of questbook commands.
    default: true
